# 公共配置文件
spring:
  application:
    name: API_BackEnd
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 默认 dev 环境
  config:
    activate:
      on-profile: dev
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pig-nest
    username: root
    password: 147895263
  # Redis 配置
  # todo 需替换配置，然后取消注释
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path:
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: AKIDm0FQdljYGnlcJrFQO8eEiLA2wsr3Maea
    secretKey: 3ynV8e4LlI1jYJ7NXbX1StZO8maWRGxz
    region: ap-nanjing
    bucket: apply-1308809307
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'API_BackEnd'
      paths-to-match: '/**'
      packages-to-scan: com.pignest.api.controller
  auto-tag-classes: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
dubbo:
  application:
    name: API_BackEnd
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
api:
  client:
    access-key: aUKeu57GjB38esJiWHdb
    secret-key: 6C9mRYYMzINC7yoa0o6fvtJIN1J9seUgxUH7fNBS